# Generated by Django 5.0.1 on 2024-02-29 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Animal",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, unique=True)),
                ("description", models.TextField(blank=True)),
                ("picture", models.ImageField(blank=True, upload_to="animal_images")),
                ("upvotes", models.IntegerField(default=0)),
                ("downvotes", models.IntegerField(default=0)),
                ("date", models.DateField(auto_now_add=True)),
                ("slug", models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("website", models.URLField(blank=True)),
                ("picture", models.ImageField(blank=True, upload_to="profile_images")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserList",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128)),
                ("date", models.DateField(auto_now_add=True)),
                ("description", models.TextField(blank=True)),
                ("upvotes", models.IntegerField(default=0)),
                ("downvotes", models.IntegerField(default=0)),
                ("slug", models.SlugField(unique=True)),
                ("animals", models.ManyToManyField(to="wildthoughts.animal")),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="authored_user_lists",
                        to="wildthoughts.userprofile",
                    ),
                ),
                (
                    "downvotes_by",
                    models.ManyToManyField(
                        related_name="downvoted_user_lists",
                        to="wildthoughts.userprofile",
                    ),
                ),
                (
                    "upvoted_by",
                    models.ManyToManyField(
                        related_name="upvoted_user_lists", to="wildthoughts.userprofile"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Discussion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128)),
                ("date", models.DateField(auto_now_add=True)),
                ("description", models.TextField(blank=True)),
                ("upvotes", models.IntegerField(default=0)),
                ("downvotes", models.IntegerField(default=0)),
                ("slug", models.SlugField(unique=True)),
                (
                    "animal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wildthoughts.animal",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="authored_discussions",
                        to="wildthoughts.userprofile",
                    ),
                ),
                (
                    "downvotes_by",
                    models.ManyToManyField(
                        related_name="downvoted_discussions",
                        to="wildthoughts.userprofile",
                    ),
                ),
                (
                    "upvoted_by",
                    models.ManyToManyField(
                        related_name="upvoted_discussions",
                        to="wildthoughts.userprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("date", models.DateField(auto_now_add=True)),
                ("upvotes", models.IntegerField(default=0)),
                ("downvotes", models.IntegerField(default=0)),
                (
                    "discussion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wildthoughts.discussion",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="authored_comments",
                        to="wildthoughts.userprofile",
                    ),
                ),
                (
                    "downvotes_by",
                    models.ManyToManyField(
                        related_name="downvoted_comments", to="wildthoughts.userprofile"
                    ),
                ),
                (
                    "upvoted_by",
                    models.ManyToManyField(
                        related_name="upvoted_comments", to="wildthoughts.userprofile"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="animal",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="authored_animals",
                to="wildthoughts.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="animal",
            name="downvotes_by",
            field=models.ManyToManyField(
                related_name="downvoted_animals", to="wildthoughts.userprofile"
            ),
        ),
        migrations.AddField(
            model_name="animal",
            name="upvoted_by",
            field=models.ManyToManyField(
                related_name="upvoted_animals", to="wildthoughts.userprofile"
            ),
        ),
    ]
