# Generated by Django 2.2.28 on 2024-03-15 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildthoughts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='downvotes_by',
            new_name='downvoted_by',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='downvotes_by',
            new_name='downvoted_by',
        ),
        migrations.RenameField(
            model_name='discussion',
            old_name='downvotes_by',
            new_name='downvoted_by',
        ),
        migrations.RenameField(
            model_name='userlist',
            old_name='downvotes_by',
            new_name='downvoted_by',
        ),
    ]
