# Generated by Django 2.2.28 on 2024-03-11 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildthoughts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='decision_maker',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
