# Generated by Django 2.2.28 on 2024-03-12 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildthoughts', '0003_userprofile_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petition',
            name='animals',
            field=models.ManyToManyField(blank=True, to='wildthoughts.Animal'),
        ),
    ]
