# Generated by Django 2.2.28 on 2024-03-12 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildthoughts', '0004_auto_20240312_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petition',
            name='goal',
            field=models.IntegerField(default=10),
        ),
    ]
